name: Build

on:
  workflow_run:
    workflows: ["Generate GitBlog README"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Init submodule
      run: |
        git submodule update --init --recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd ./Maverick
        python -m pip install --upgrade pip
        pip install -r prod_req.txt

    - name: Get build cache
      uses: actions/checkout@v4
      with:
        ref: 'cache'
        path: './build_cache'
      continue-on-error: true

    - name: Build site
      run: |
        mkdir -p ./Maverick/cached_imgs
        if [ -f ./build_cache/sizeinfo.json ]; then
          cp ./build_cache/sizeinfo.json ./Maverick/cached_imgs
        fi
        rm -rf ./build_cache/.git 2>/dev/null || true

        cd ./Maverick
        python ./build.py -c "../conf.py"

        cd ..
        mkdir -p ./build_cache
        cp ./Maverick/cached_imgs/sizeinfo.json ./build_cache 2>/dev/null || true

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./dist
        allow_empty_commit: false

    - name: Save build cache
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: cache
        publish_dir: ./build_cache
        allow_empty_commit: false
